
version: 2

models:
  - name: customers
    description: "customers table"
    columns:
      - name: id
        data_type: string
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: name
        data_type: string
        description: "The customer name"
        data_tests:
          - not_null

  # - name: my_second_dbt_model
  #   description: "A starter dbt model"
  #   columns:
  #     - name: id
  #       description: "The primary key for this table"
  #       data_tests:
  #         - unique
  #         - not_null
